apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: n2w4ec7br-go 
  janus-idp.io/tekton: n2w4ec7br-go
  backstage.io/kubernetes-id: n2w4ec7br-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n2w4ec7br-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  